### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by kehwar** [wobsoriano/nuxt-remote-fn#4] opened 2023-01-17 23:19 UTC
I'm getting the following error on my project:

`[worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

Node: v16.14.2

My package:

````
"devDependencies": {
        "@nuxt/test-utils": "^3.0.0",
        "@types/file-saver": "^2.0.5",
        "@types/lodash": "^4.14.191",
        "@types/mssql": "^8.1.1",
        "@vitest/ui": "^0.26.3",
        "@vueuse/nuxt": "^9.9.0",
        "nuxt": "^3.0.0",
        "sass": "^1.57.1",
        "vite-tsconfig-paths": "^4.0.3",
        "vitest": "^0.26.3"
    },
    "dependencies": {
        "@casl/ability": "^6.3.3",
        "@trpc/client": "^10.7.0",
        "@trpc/server": "^10.7.0",
        "@vueuse/core": "^9.3.1",
        "@vueuse/firebase": "^9.9.0",
        "axios": "^1.2.1",
        "chart.js": "^3.9.1",
        "dayjs": "^1.11.7",
        "file-saver": "^2.0.5",
        "firebase": "^9.15.0",
        "firebase-admin": "^11.4.1",
        "knex": "^2.3.0",
        "lodash": "^4.17.21",
        "lru-cache": "^7.14.1",
        "mssql": "^9.0.1",
        "pino": "^8.8.0",
        "pino-pretty": "^9.1.1",
        "primeflex": "^3.3.0",
        "primeicons": "^6.0.1",
        "primevue": "^3.21.0",
        "quill": "^1.3.7",
        "round-to": "^6.0.0",
        "trpc-nuxt": "^0.4.4",
        "vuefire": "^3.0.0",
        "xlsx": "^0.18.5",
        "xml2js-parser": "^1.1.1",
        "zod": "^3.20.2"
    }
````

I'm going to try this with a minimal start next

I have been using nuxt-trpc without issues (thanks!) but I would really like to get this working

**Comment by kehwar** [comment] 2023-01-18 03:07
I tried a new Nuxt Project with only this module and the same error ocurred

I updated node to version v18.13 and still doesn't work

I cloned the project and ran the playground and it works

I made my minimal test on stackblitz and it works: https://stackblitz.com/edit/nuxt-starter-97d4nq?file=app.vue

Don't know what else to try

**Comment by kehwar** [comment] 2023-01-18 03:16
https://github.com/nuxt/framework/issues/9092

**Comment by therealokoro** [comment] 2023-01-20 23:28
Plus one on this. Same error

**Comment by wobsoriano** [comment] 2023-01-21 04:18
Oh. Going to test this on my Windows machine. Works fine on Mac!

**Comment by wobsoriano** [comment] 2023-01-25 06:27
Nuxt 3.1.0 is out. Can you try and see if the error still persists? Thanks!

https://github.com/nuxt/nuxt/releases/tag/v3.1.0

```bash
npx nuxi@latest upgrade --force
```

**Comment by wobsoriano** [comment] 2023-01-30 17:08
Published v0.2.0.

Can anyone confirm if the issue is fixed on Windows? Thanks!

**Comment by wobsoriano** [comment] 2023-01-30 18:59
Tested on Windows:

```bash
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `nuxt-remote-fn@0.2.1`
- Build Modules:    `-`
```

Build success.

**Closed by wobsoriano** 2023-01-30 18:59 UTC

**Comment by kehwar** [comment] 2023-02-05 16:22
Sorry for not keeping up

```
- Operating System: `Windows 10`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- Modules:  `nuxt-remote-fn@0.2.1`
```

Build sucess.
